/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Ciego_enemy(props) {
    const { nodes, materials } = useGLTF('/Portfolio_react/models/Ciego_enemy.glb')
    return (
    <group {...props} dispose={null}>
        <mesh
        castShadow
        receiveShadow
        geometry={nodes.blind_enemy.geometry}
        material={materials.polySurface22SG}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.2}
        />
    </group>
    )
}

useGLTF.preload('//Portfolio_react/models/Ciego_enemy.glb')
