/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Warrior(props) {
  const { nodes, materials } = useGLTF('/Portfolio_react/models/warrior_blender.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.guerrero.geometry}
        material={materials.guerreroMAT}
      />
    </group>
  )
}

useGLTF.preload('/models/warrior_blender.glb')
